// <auto-generated />
using System;
using BetterBuiltWorkouts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BetterBuiltWorkouts.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220427181239_Add Plan Images")]
    partial class AddPlanImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "710a1ebb-07d1-40cb-b5f5-dea1b53d2646",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55211522-9cb8-47d4-97dd-0fc2a4ac4e1a",
                            Email = "drewxcom@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Drew",
                            LastName = "Crawford",
                            LockoutEnabled = false,
                            NormalizedEmail = "DREWXCOM@GMAIL.COM",
                            NormalizedUserName = "DREWXCOM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPVJXD0330S8bfPyQPNshz/clgvvumtritJSRVMPDeP3Q9Oj3rncv/q7bscQ00Sn9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9135632-0406-4605-b137-32ab2895e4b9",
                            TwoFactorEnabled = false,
                            UserName = "drewxcom"
                        },
                        new
                        {
                            Id = "de0bee9a-a679-40a0-8bd3-1f5229cd7a64",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e74b91da-04e9-4fd4-bfb6-e43c76653364",
                            Email = "hale.l.c91@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Cody",
                            LastName = "Hale",
                            LockoutEnabled = false,
                            NormalizedEmail = "HALE.L.C91@GMAIL.COM",
                            NormalizedUserName = "CHALE",
                            PasswordHash = "AQAAAAEAACcQAAAAEJH41Xzi72W2XA4IAZUcw0yOx2FT4YtEY9LnPUaCs6rkNccJXpNyKAmMLcZ/7EJ2/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "174504d5-a20e-48f2-bab7-4769fa7cc982",
                            TwoFactorEnabled = false,
                            UserName = "chale"
                        },
                        new
                        {
                            Id = "e34e3a7e-a559-44ea-bbc9-74a708b04d77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c096957-8825-49d8-8d6c-d6ed5e7dd9a7",
                            Email = "Karamuja.sabina@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sabina",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "KARAMUJA.SABINA@GMAIL.COM",
                            NormalizedUserName = "SKARAMUJA",
                            PasswordHash = "AQAAAAEAACcQAAAAEH6JWIQyCX/Ln7fqVADgimBwD8KvSYEbww7xPC8E93uUf2z9a2ChI6AfX9KKLWZXug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c574fe7b-4df6-4dd4-9214-5f070b12b0f9",
                            TwoFactorEnabled = false,
                            UserName = "skaramuja"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distance")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ExerciseTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Reps")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Time")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Weight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("ExerciseTypeID");

                    b.HasIndex("PlanId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BackExtension.png",
                            Name = "Back Extension"
                        },
                        new
                        {
                            ExerciseId = 2,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "BandedTriplanarToeTaps.png",
                            Name = "Banded Triplanar Toe Taps"
                        },
                        new
                        {
                            ExerciseId = 3,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Basketball.png",
                            Name = "Basketball"
                        },
                        new
                        {
                            ExerciseId = 4,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BenchPress.png",
                            Name = "Bench Press",
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 5,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BicepCurl.png",
                            Name = "Bicep Curl",
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 6,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Biking.png",
                            Name = "Biking",
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 7,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "BriskWalking.png",
                            Name = "Brisk Walking"
                        },
                        new
                        {
                            ExerciseId = 8,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "CalfStretch.png",
                            Name = "Calf Stretch",
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 9,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "CardioClass.png",
                            Name = "Cardio Class"
                        },
                        new
                        {
                            ExerciseId = 10,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "CardioMachine.png",
                            Name = "Cardio Machine"
                        },
                        new
                        {
                            ExerciseId = 11,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ChestFly.png",
                            Name = "Chest Fly"
                        },
                        new
                        {
                            ExerciseId = 12,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Crunches.png",
                            Name = "Crunches"
                        },
                        new
                        {
                            ExerciseId = 13,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Dancing.png",
                            Name = "Dancing"
                        },
                        new
                        {
                            ExerciseId = 14,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Deadlift.png",
                            Name = "Deadlift"
                        },
                        new
                        {
                            ExerciseId = 15,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "FlamingoStand.png",
                            Name = "Flamingo Stand"
                        },
                        new
                        {
                            ExerciseId = 16,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "GardeningAndWeeding.png",
                            Name = "Gardening"
                        },
                        new
                        {
                            ExerciseId = 17,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Golf.png",
                            Name = "Golf"
                        },
                        new
                        {
                            ExerciseId = 18,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "HamstringStretch.png",
                            Name = "Hamstring Stretch",
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 19,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "HeelToToeWalk.png",
                            Name = "Heel-to-Toe Walk"
                        },
                        new
                        {
                            ExerciseId = 20,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "HighIntensityIntervalTraining.png",
                            Name = "HIIT"
                        },
                        new
                        {
                            ExerciseId = 21,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Hiking.png",
                            Name = "Hiking"
                        },
                        new
                        {
                            ExerciseId = 22,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "HipFlexorsStretch.png",
                            Name = "Hip Flexors Stretch"
                        },
                        new
                        {
                            ExerciseId = 23,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "JoggingOrRunning.png",
                            Name = "Jogging or Running",
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 24,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "KneeToChestStretch.png",
                            Name = "Knee-to-Chest Stretch"
                        },
                        new
                        {
                            ExerciseId = 25,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LateralRaise.png",
                            Name = "Lateral Raise",
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 26,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LegCurl.png",
                            Name = "Leg Curl"
                        },
                        new
                        {
                            ExerciseId = 27,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LegExtension.png",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            ExerciseId = 28,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LegPress.png",
                            Name = "Leg Press"
                        },
                        new
                        {
                            ExerciseId = 29,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Lunge.png",
                            Name = "Lunge"
                        },
                        new
                        {
                            ExerciseId = 30,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "LiftingWeights.png",
                            Name = "Lifting Weights"
                        },
                        new
                        {
                            ExerciseId = 31,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "NeckStretch.png",
                            Name = "Neck Stretch",
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 32,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "Pilates.png",
                            Name = "Pilates"
                        },
                        new
                        {
                            ExerciseId = 33,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "PullDown.png",
                            Name = "Pull-down"
                        },
                        new
                        {
                            ExerciseId = 34,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "PullUp.png",
                            Name = "Pull-up"
                        },
                        new
                        {
                            ExerciseId = 35,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "PushUps.png",
                            Name = "Push-ups"
                        },
                        new
                        {
                            ExerciseId = 36,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "QuadricepsStretch.png",
                            Name = "Quadriceps Stretch"
                        },
                        new
                        {
                            ExerciseId = 37,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "ResistanceExercise.png",
                            Name = "Elastic Bands or Tubes"
                        },
                        new
                        {
                            ExerciseId = 38,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Rowing.png",
                            Name = "Rowing"
                        },
                        new
                        {
                            ExerciseId = 39,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "SeatedCalfRaise.png",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 40,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderPress.png",
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            ExerciseId = 41,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderShrug.png",
                            Name = "Shoulder Shrug"
                        },
                        new
                        {
                            ExerciseId = 42,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "ShoulderStretch.png",
                            Name = "Shoulder Stretch"
                        },
                        new
                        {
                            ExerciseId = 43,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Soccer.png",
                            Name = "Soccer"
                        },
                        new
                        {
                            ExerciseId = 44,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Squat.png",
                            Name = "Squat"
                        },
                        new
                        {
                            ExerciseId = 45,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Stairs.png",
                            Name = "Stairs"
                        },
                        new
                        {
                            ExerciseId = 46,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "StandingCalfRaise.png",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 47,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "StrengthClass.png",
                            Name = "Strength Class"
                        },
                        new
                        {
                            ExerciseId = 48,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Swimming.png",
                            Name = "Swimming",
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 49,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "TaiChi.png",
                            Name = "Tai Chi"
                        },
                        new
                        {
                            ExerciseId = 50,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Tennis.png",
                            Name = "Tennis"
                        },
                        new
                        {
                            ExerciseId = 51,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "TightropeWalk.png",
                            Name = "Tightrope Walk"
                        },
                        new
                        {
                            ExerciseId = 52,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "TricepExtension.png",
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            ExerciseId = 53,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "UltimateFrisbee.png",
                            Name = "Ultimate Frisbee"
                        },
                        new
                        {
                            ExerciseId = 54,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "UprightRow.png",
                            Name = "Upright Row"
                        },
                        new
                        {
                            ExerciseId = 55,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Volleyball.png",
                            Name = "Volleyball"
                        },
                        new
                        {
                            ExerciseId = 56,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "WalkingWithStroller.png",
                            Name = "Walking with a Stroller"
                        },
                        new
                        {
                            ExerciseId = 57,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Yoga.png",
                            Name = "Yoga"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Property<string>("ExerciseTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseTypeID");

                    b.ToTable("ExerciseTypes");

                    b.HasData(
                        new
                        {
                            ExerciseTypeID = "aerobic",
                            Name = "Aerobic"
                        },
                        new
                        {
                            ExerciseTypeID = "strength_training",
                            Name = "Strength Training"
                        },
                        new
                        {
                            ExerciseTypeID = "streching",
                            Name = "Stretching"
                        },
                        new
                        {
                            ExerciseTypeID = "balance",
                            Name = "Balance"
                        },
                        new
                        {
                            ExerciseTypeID = "other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            CreatedBy = "Better Built Systems",
                            Image = "LiftingPlan",
                            Name = "Example Plan 1"
                        },
                        new
                        {
                            PlanId = 2,
                            CreatedBy = "Better Built Systems",
                            Image = "CardioPlan",
                            Name = "Example Plan 2"
                        },
                        new
                        {
                            PlanId = 3,
                            CreatedBy = "Better Built Systems",
                            Image = "StretchingPlan",
                            Name = "Example Plan 3"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkoutId");

                    b.HasIndex("PlanId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "e6f10cd8-9d76-4533-8db0-e81fd2ad8b54",
                            ConcurrencyStamp = "e6f10cd8-9d76-4533-8db0-e81fd2ad8b54",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7d4dcdb4-e462-4cd3-b649-81d90dd91de1",
                            ConcurrencyStamp = "7d4dcdb4-e462-4cd3-b649-81d90dd91de1",
                            Name = "Suspended",
                            NormalizedName = "SUSPENDED"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "710a1ebb-07d1-40cb-b5f5-dea1b53d2646",
                            RoleId = "e6f10cd8-9d76-4533-8db0-e81fd2ad8b54"
                        },
                        new
                        {
                            UserId = "de0bee9a-a679-40a0-8bd3-1f5229cd7a64",
                            RoleId = "e6f10cd8-9d76-4533-8db0-e81fd2ad8b54"
                        },
                        new
                        {
                            UserId = "e34e3a7e-a559-44ea-bbc9-74a708b04d77",
                            RoleId = "e6f10cd8-9d76-4533-8db0-e81fd2ad8b54"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ExerciseType", "ExerciseType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.Plan", "Plan")
                        .WithMany("Exercises")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExerciseType");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Workout", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Plan", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
