// <auto-generated />
using System;
using BetterBuiltWorkouts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BetterBuiltWorkouts.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220407170233_update-models")]
    partial class updatemodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "dd05b536-933a-490d-9899-9f8c061cfe48",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57bdf0a5-6120-4d2d-9e8a-3ae8634b4796",
                            Email = "drewxcom@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Drew",
                            LastName = "Crawford",
                            LockoutEnabled = false,
                            NormalizedEmail = "DREWXCOM@GMAIL.COM",
                            NormalizedUserName = "DREWXCOM",
                            PasswordHash = "AQAAAAEAACcQAAAAELn62fCxupQ7mHiV+U25T3o7RO57k0IaMu7+ClrxC065KsRauXs19qD93lmi8ynPAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8152b928-8f97-41db-aaab-70f77586c894",
                            TwoFactorEnabled = false,
                            UserName = "drewxcom"
                        },
                        new
                        {
                            Id = "2db08e46-b1da-4baf-b361-4d05ad25771d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa7d235c-af3e-492d-9dcb-1931aff22fcf",
                            Email = "hale.l.c91@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Cody",
                            LastName = "Hale",
                            LockoutEnabled = false,
                            NormalizedEmail = "HALE.L.C91@GMAIL.COM",
                            NormalizedUserName = "CHALE",
                            PasswordHash = "AQAAAAEAACcQAAAAELX6BFLa/hU76w5mqDep2hByCrFU1/l3WbsW8TwUmJVVWfmryYy5x1JedxJnHNXiqA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6bd41edf-f101-4bc4-9b6f-b90379093e95",
                            TwoFactorEnabled = false,
                            UserName = "chale"
                        },
                        new
                        {
                            Id = "9b83dac5-f553-4194-b8e9-cdee7f9753a8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d72772fc-bb89-462b-a1f5-b45dd9b25b36",
                            Email = "Karamuja.sabina@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sabina",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "KARAMUJA.SABINA@GMAIL.COM",
                            NormalizedUserName = "SKARAMUJA",
                            PasswordHash = "AQAAAAEAACcQAAAAEGgrZXBtpY6DAfyBOo4U0MGVdo1kE14ghD4xal/nJdvQC+QaKmSZCpdPfmiv0xSl+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c47f10a7-7eae-4e9a-8ca2-9137d2696d42",
                            TwoFactorEnabled = false,
                            UserName = "skaramuja"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distance")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ExerciseTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reps")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Time")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Weight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("ExerciseTypeID");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            ExerciseTypeID = "strength_training",
                            Image = "BackExtension.png",
                            IsPublic = true,
                            Name = "Back Extension"
                        },
                        new
                        {
                            ExerciseId = 2,
                            ExerciseTypeID = "aerobic",
                            Image = "Basketball.png",
                            IsPublic = true,
                            Name = "Basketball"
                        },
                        new
                        {
                            ExerciseId = 3,
                            ExerciseTypeID = "strength_training",
                            Image = "BenchPress.png",
                            IsPublic = true,
                            Name = "Bench Press"
                        },
                        new
                        {
                            ExerciseId = 4,
                            ExerciseTypeID = "strength_training",
                            Image = "BicepCurl.png",
                            IsPublic = true,
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            ExerciseId = 5,
                            ExerciseTypeID = "aerobic",
                            Image = "Biking.png",
                            IsPublic = true,
                            Name = "Biking"
                        },
                        new
                        {
                            ExerciseId = 6,
                            ExerciseTypeID = "aerobic",
                            Image = "BriskWalking.png",
                            IsPublic = true,
                            Name = "Brisk Walking"
                        },
                        new
                        {
                            ExerciseId = 7,
                            ExerciseTypeID = "aerobic",
                            Image = "CardioClass.png",
                            IsPublic = true,
                            Name = "Cardio Class"
                        },
                        new
                        {
                            ExerciseId = 8,
                            ExerciseTypeID = "aerobic",
                            Image = "CardioMachine.png",
                            IsPublic = true,
                            Name = "Cardio Machine"
                        },
                        new
                        {
                            ExerciseId = 9,
                            ExerciseTypeID = "strength_training",
                            Image = "ChestFly.png",
                            IsPublic = true,
                            Name = "Chest Fly"
                        },
                        new
                        {
                            ExerciseId = 10,
                            ExerciseTypeID = "strength_training",
                            Image = "Crunches.png",
                            IsPublic = true,
                            Name = "Crunches"
                        },
                        new
                        {
                            ExerciseId = 11,
                            ExerciseTypeID = "aerobic",
                            Image = "Dancing.png",
                            IsPublic = true,
                            Name = "Dancing"
                        },
                        new
                        {
                            ExerciseId = 12,
                            ExerciseTypeID = "strength_training",
                            Image = "Deadlift.png",
                            IsPublic = true,
                            Name = "Deadlift"
                        },
                        new
                        {
                            ExerciseId = 13,
                            ExerciseTypeID = "aerobic",
                            Image = "GardeningAndWeeding.png",
                            IsPublic = true,
                            Name = "Gardening and Weeding"
                        },
                        new
                        {
                            ExerciseId = 14,
                            ExerciseTypeID = "aerobic",
                            Image = "Golf.png",
                            IsPublic = true,
                            Name = "Golf"
                        },
                        new
                        {
                            ExerciseId = 15,
                            ExerciseTypeID = "aerobic",
                            Image = "HighIntensityIntervalTraining.png",
                            IsPublic = true,
                            Name = "High-Intensity Interval Training"
                        },
                        new
                        {
                            ExerciseId = 16,
                            ExerciseTypeID = "aerobic",
                            Image = "Hiking.png",
                            IsPublic = true,
                            Name = "Hiking"
                        },
                        new
                        {
                            ExerciseId = 17,
                            ExerciseTypeID = "aerobic",
                            Image = "JoggingOrRunning.png",
                            IsPublic = true,
                            Name = "Jogging or Running"
                        },
                        new
                        {
                            ExerciseId = 18,
                            ExerciseTypeID = "strength_training",
                            Image = "LateralRaise.png",
                            IsPublic = true,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            ExerciseId = 19,
                            ExerciseTypeID = "strength_training",
                            Image = "LegCurl.png",
                            IsPublic = true,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            ExerciseId = 20,
                            ExerciseTypeID = "strength_training",
                            Image = "LegExtension.png",
                            IsPublic = true,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            ExerciseId = 21,
                            ExerciseTypeID = "strength_training",
                            Image = "LegPress.png",
                            IsPublic = true,
                            Name = "Leg Press"
                        },
                        new
                        {
                            ExerciseId = 22,
                            ExerciseTypeID = "strength_training",
                            Image = "Lunge.png",
                            IsPublic = true,
                            Name = "Lunge"
                        },
                        new
                        {
                            ExerciseId = 23,
                            ExerciseTypeID = "aerobic",
                            Image = "LiftingWeights.png",
                            IsPublic = true,
                            Name = "Lifting Weights"
                        },
                        new
                        {
                            ExerciseId = 24,
                            ExerciseTypeID = "balance",
                            Image = "Pilates.png",
                            IsPublic = true,
                            Name = "Pilates"
                        },
                        new
                        {
                            ExerciseId = 25,
                            ExerciseTypeID = "strength_training",
                            Image = "PullDown.png",
                            IsPublic = true,
                            Name = "Pull-down"
                        },
                        new
                        {
                            ExerciseId = 26,
                            ExerciseTypeID = "strength_training",
                            Image = "PullUp.png",
                            IsPublic = true,
                            Name = "Pull-up"
                        },
                        new
                        {
                            ExerciseId = 27,
                            ExerciseTypeID = "strength_training",
                            Image = "PushUps.png",
                            IsPublic = true,
                            Name = "Push-ups"
                        },
                        new
                        {
                            ExerciseId = 28,
                            ExerciseTypeID = "aerobic",
                            Image = "ResistanceExercise.png",
                            IsPublic = true,
                            Name = "Resistance Exercise with Elastic Bands or Tubes"
                        },
                        new
                        {
                            ExerciseId = 29,
                            ExerciseTypeID = "aerobic",
                            Image = "Rowing.png",
                            IsPublic = true,
                            Name = "Rowing"
                        },
                        new
                        {
                            ExerciseId = 30,
                            ExerciseTypeID = "strength_training",
                            Image = "SeatedCalfRaise.png",
                            IsPublic = true,
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 31,
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderPress.png",
                            IsPublic = true,
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            ExerciseId = 32,
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderShrug.png",
                            IsPublic = true,
                            Name = "Shoulder Shrug"
                        },
                        new
                        {
                            ExerciseId = 33,
                            ExerciseTypeID = "aerobic",
                            Image = "Soccer.png",
                            IsPublic = true,
                            Name = "Soccer"
                        },
                        new
                        {
                            ExerciseId = 34,
                            ExerciseTypeID = "strength_training",
                            Image = "Squat.png",
                            IsPublic = true,
                            Name = "Squat"
                        },
                        new
                        {
                            ExerciseId = 35,
                            ExerciseTypeID = "aerobic",
                            Image = "Stairs.png",
                            IsPublic = true,
                            Name = "Stairs"
                        },
                        new
                        {
                            ExerciseId = 36,
                            ExerciseTypeID = "strength_training",
                            Image = "StandingCalfRaise.png",
                            IsPublic = true,
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 37,
                            ExerciseTypeID = "aerobic",
                            Image = "StrengthClass.png",
                            IsPublic = true,
                            Name = "Strength Class"
                        },
                        new
                        {
                            ExerciseId = 38,
                            ExerciseTypeID = "aerobic",
                            Image = "Swimming.png",
                            IsPublic = true,
                            Name = "Swimming"
                        },
                        new
                        {
                            ExerciseId = 39,
                            ExerciseTypeID = "balance",
                            Image = "TaiChi.png",
                            IsPublic = true,
                            Name = "Tai Chi"
                        },
                        new
                        {
                            ExerciseId = 40,
                            ExerciseTypeID = "aerobic",
                            Image = "Tennis.png",
                            IsPublic = true,
                            Name = "Tennis"
                        },
                        new
                        {
                            ExerciseId = 41,
                            ExerciseTypeID = "strength_training",
                            Image = "TricepExtension.png",
                            IsPublic = true,
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            ExerciseId = 42,
                            ExerciseTypeID = "aerobic",
                            Image = "UltimateFrisbee.png",
                            IsPublic = true,
                            Name = "Ultimate Frisbee"
                        },
                        new
                        {
                            ExerciseId = 43,
                            ExerciseTypeID = "strength_training",
                            Image = "UprightRow.png",
                            IsPublic = true,
                            Name = "Upright Row"
                        },
                        new
                        {
                            ExerciseId = 44,
                            ExerciseTypeID = "aerobic",
                            Image = "Volleyball.png",
                            IsPublic = true,
                            Name = "Volleyball"
                        },
                        new
                        {
                            ExerciseId = 45,
                            ExerciseTypeID = "aerobic",
                            Image = "WalkingWithStroller.png",
                            IsPublic = true,
                            Name = "Walking with a Stroller"
                        },
                        new
                        {
                            ExerciseId = 46,
                            ExerciseTypeID = "aerobic",
                            Image = "Yoga.png",
                            IsPublic = true,
                            Name = "Yoga"
                        },
                        new
                        {
                            ExerciseId = 47,
                            ExerciseTypeID = "streching",
                            Image = "CalfStretch.png",
                            IsPublic = true,
                            Name = "Calf Stretch"
                        },
                        new
                        {
                            ExerciseId = 48,
                            ExerciseTypeID = "streching",
                            Image = "HamstringStretch.png",
                            IsPublic = true,
                            Name = "Hamstring Stretch"
                        },
                        new
                        {
                            ExerciseId = 49,
                            ExerciseTypeID = "streching",
                            Image = "QuadricepsStretch.png",
                            IsPublic = true,
                            Name = "Quadriceps Stretch"
                        },
                        new
                        {
                            ExerciseId = 50,
                            ExerciseTypeID = "streching",
                            Image = "HipFlexorsStretch.png",
                            IsPublic = true,
                            Name = "Hip Flexors Stretch"
                        },
                        new
                        {
                            ExerciseId = 51,
                            ExerciseTypeID = "streching",
                            Image = "KneeToChestStretch.png",
                            IsPublic = true,
                            Name = "Knee-to-Chest Stretch"
                        },
                        new
                        {
                            ExerciseId = 52,
                            ExerciseTypeID = "streching",
                            Image = "ShoulderStretch.png",
                            IsPublic = true,
                            Name = "Shoulder Stretch"
                        },
                        new
                        {
                            ExerciseId = 53,
                            ExerciseTypeID = "streching",
                            Image = "NeckStretch.png",
                            IsPublic = true,
                            Name = "Neck Stretch"
                        },
                        new
                        {
                            ExerciseId = 54,
                            ExerciseTypeID = "balance",
                            Image = "TightropeWalk.png",
                            IsPublic = true,
                            Name = "Tightrope Walk"
                        },
                        new
                        {
                            ExerciseId = 55,
                            ExerciseTypeID = "balance",
                            Image = "FlamingoStand.png",
                            IsPublic = true,
                            Name = "Flamingo Stand"
                        },
                        new
                        {
                            ExerciseId = 56,
                            ExerciseTypeID = "balance",
                            Image = "HeelToToeWalk.png",
                            IsPublic = true,
                            Name = "Heel-to-Toe Walk"
                        },
                        new
                        {
                            ExerciseId = 57,
                            ExerciseTypeID = "balance",
                            Image = "BandedTriplanarToeTaps.png",
                            IsPublic = true,
                            Name = "Banded Triplanar Toe Taps"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExercisePlan", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("ExercisePlans");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 2,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 3,
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 4,
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 5,
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 6,
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 7,
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 8,
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 9,
                            PlanId = 3
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Property<string>("ExerciseTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseTypeID");

                    b.ToTable("ExerciseTypes");

                    b.HasData(
                        new
                        {
                            ExerciseTypeID = "aerobic",
                            Name = "Aerobic"
                        },
                        new
                        {
                            ExerciseTypeID = "strength_training",
                            Name = "Strength Training"
                        },
                        new
                        {
                            ExerciseTypeID = "streching",
                            Name = "Stretching"
                        },
                        new
                        {
                            ExerciseTypeID = "balance",
                            Name = "Balance"
                        },
                        new
                        {
                            ExerciseTypeID = "other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimesCompleted")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            CreatedBy = "Better Built Systems",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Default Plan 1",
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PlanId = 2,
                            CreatedBy = "Better Built Systems",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Default Plan 2",
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PlanId = 3,
                            CreatedBy = "Better Built Systems",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Default Plan 3",
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ExercisePlan", b =>
                {
                    b.Property<int>("ExercisesExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("PlansPlanId")
                        .HasColumnType("int");

                    b.HasKey("ExercisesExerciseId", "PlansPlanId");

                    b.HasIndex("PlansPlanId");

                    b.ToTable("ExercisePlan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "bbaa3fe9-62fa-4583-9924-fd3e7ca02d32",
                            ConcurrencyStamp = "bbaa3fe9-62fa-4583-9924-fd3e7ca02d32",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6e13213e-6be5-49f5-a8df-227e62a6a183",
                            ConcurrencyStamp = "6e13213e-6be5-49f5-a8df-227e62a6a183",
                            Name = "Suspended",
                            NormalizedName = "SUSPENDED"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "dd05b536-933a-490d-9899-9f8c061cfe48",
                            RoleId = "bbaa3fe9-62fa-4583-9924-fd3e7ca02d32"
                        },
                        new
                        {
                            UserId = "2db08e46-b1da-4baf-b361-4d05ad25771d",
                            RoleId = "bbaa3fe9-62fa-4583-9924-fd3e7ca02d32"
                        },
                        new
                        {
                            UserId = "9b83dac5-f553-4194-b8e9-cdee7f9753a8",
                            RoleId = "bbaa3fe9-62fa-4583-9924-fd3e7ca02d32"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ExerciseType", "ExerciseType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExercisePlan", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.Exercise", "Exercise")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.Plan", "Plan")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ExercisePlan", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlansPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.Navigation("ExercisePlans");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Plan", b =>
                {
                    b.Navigation("ExercisePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
