// <auto-generated />
using System;
using BetterBuiltWorkouts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BetterBuiltWorkouts.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220419160206_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "6de9e11d-f012-450a-8dc2-8ae58d510403",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "138c920a-4d5c-44cf-91a3-d6fcf8d9b3b7",
                            Email = "drewxcom@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Drew",
                            LastName = "Crawford",
                            LockoutEnabled = false,
                            NormalizedEmail = "DREWXCOM@GMAIL.COM",
                            NormalizedUserName = "DREWXCOM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEt+sWNWr8yrU0VKPtg48pC9QpuUK1gvi4amIdwI44AAHnNQJIbEHDaD+GcRL63zxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f44b440-222e-412c-a399-61643f666608",
                            TwoFactorEnabled = false,
                            UserName = "drewxcom"
                        },
                        new
                        {
                            Id = "3e45d3e9-4d3c-4e20-9ace-e3d32a554134",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d46649fd-b659-4272-965c-719b1b58e9fa",
                            Email = "hale.l.c91@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Cody",
                            LastName = "Hale",
                            LockoutEnabled = false,
                            NormalizedEmail = "HALE.L.C91@GMAIL.COM",
                            NormalizedUserName = "CHALE",
                            PasswordHash = "AQAAAAEAACcQAAAAEG+NkD0roVTv0/uXbyVozi9Z71Er2uSC3Ul6xpMKSqqgQAljLou7A/hGqvwm2dVOjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e1434804-7a6b-4b31-a959-8305fa1f2b76",
                            TwoFactorEnabled = false,
                            UserName = "chale"
                        },
                        new
                        {
                            Id = "f0f0ae27-d4f3-45ea-a383-e0a919a41462",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "121a6103-08d8-4e0c-8e94-d55207f41201",
                            Email = "Karamuja.sabina@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sabina",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "KARAMUJA.SABINA@GMAIL.COM",
                            NormalizedUserName = "SKARAMUJA",
                            PasswordHash = "AQAAAAEAACcQAAAAEHR0XHmx3gimo3ta5Z7ZTU05+PQdohouC8jO5qLJ7dKHiRO+IykDxz5F61cbVfyo8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cfab60da-771a-44bd-97e8-0f5f4cc7b1ad",
                            TwoFactorEnabled = false,
                            UserName = "skaramuja"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distance")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ExerciseTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Reps")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Time")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Weight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("ExerciseTypeID");

                    b.HasIndex("PlanId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BackExtension.png",
                            Name = "Back Extension"
                        },
                        new
                        {
                            ExerciseId = 2,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Basketball.png",
                            Name = "Basketball"
                        },
                        new
                        {
                            ExerciseId = 3,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BenchPress.png",
                            Name = "Bench Press"
                        },
                        new
                        {
                            ExerciseId = 4,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BicepCurl.png",
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            ExerciseId = 5,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Biking.png",
                            Name = "Biking"
                        },
                        new
                        {
                            ExerciseId = 6,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "BriskWalking.png",
                            Name = "Brisk Walking"
                        },
                        new
                        {
                            ExerciseId = 7,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "CardioClass.png",
                            Name = "Cardio Class"
                        },
                        new
                        {
                            ExerciseId = 8,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "CardioMachine.png",
                            Name = "Cardio Machine"
                        },
                        new
                        {
                            ExerciseId = 9,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ChestFly.png",
                            Name = "Chest Fly"
                        },
                        new
                        {
                            ExerciseId = 10,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Crunches.png",
                            Name = "Crunches"
                        },
                        new
                        {
                            ExerciseId = 11,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Dancing.png",
                            Name = "Dancing"
                        },
                        new
                        {
                            ExerciseId = 12,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Deadlift.png",
                            Name = "Deadlift"
                        },
                        new
                        {
                            ExerciseId = 13,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "GardeningAndWeeding.png",
                            Name = "Gardening and Weeding"
                        },
                        new
                        {
                            ExerciseId = 14,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Golf.png",
                            Name = "Golf"
                        },
                        new
                        {
                            ExerciseId = 15,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "HighIntensityIntervalTraining.png",
                            Name = "High-Intensity Interval Training"
                        },
                        new
                        {
                            ExerciseId = 16,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Hiking.png",
                            Name = "Hiking"
                        },
                        new
                        {
                            ExerciseId = 17,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "JoggingOrRunning.png",
                            Name = "Jogging or Running"
                        },
                        new
                        {
                            ExerciseId = 18,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LateralRaise.png",
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            ExerciseId = 19,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LegCurl.png",
                            Name = "Leg Curl"
                        },
                        new
                        {
                            ExerciseId = 20,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LegExtension.png",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            ExerciseId = 21,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "LegPress.png",
                            Name = "Leg Press"
                        },
                        new
                        {
                            ExerciseId = 22,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Lunge.png",
                            Name = "Lunge"
                        },
                        new
                        {
                            ExerciseId = 23,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "LiftingWeights.png",
                            Name = "Lifting Weights"
                        },
                        new
                        {
                            ExerciseId = 24,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "Pilates.png",
                            Name = "Pilates"
                        },
                        new
                        {
                            ExerciseId = 25,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "PullDown.png",
                            Name = "Pull-down"
                        },
                        new
                        {
                            ExerciseId = 26,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "PullUp.png",
                            Name = "Pull-up"
                        },
                        new
                        {
                            ExerciseId = 27,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "PushUps.png",
                            Name = "Push-ups"
                        },
                        new
                        {
                            ExerciseId = 28,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "ResistanceExercise.png",
                            Name = "Resistance Exercise with Elastic Bands or Tubes"
                        },
                        new
                        {
                            ExerciseId = 29,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Rowing.png",
                            Name = "Rowing"
                        },
                        new
                        {
                            ExerciseId = 30,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "SeatedCalfRaise.png",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 31,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderPress.png",
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            ExerciseId = 32,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderShrug.png",
                            Name = "Shoulder Shrug"
                        },
                        new
                        {
                            ExerciseId = 33,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Soccer.png",
                            Name = "Soccer"
                        },
                        new
                        {
                            ExerciseId = 34,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "Squat.png",
                            Name = "Squat"
                        },
                        new
                        {
                            ExerciseId = 35,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Stairs.png",
                            Name = "Stairs"
                        },
                        new
                        {
                            ExerciseId = 36,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "StandingCalfRaise.png",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 37,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "StrengthClass.png",
                            Name = "Strength Class"
                        },
                        new
                        {
                            ExerciseId = 38,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Swimming.png",
                            Name = "Swimming"
                        },
                        new
                        {
                            ExerciseId = 39,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "TaiChi.png",
                            Name = "Tai Chi"
                        },
                        new
                        {
                            ExerciseId = 40,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Tennis.png",
                            Name = "Tennis"
                        },
                        new
                        {
                            ExerciseId = 41,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "TricepExtension.png",
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            ExerciseId = 42,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "UltimateFrisbee.png",
                            Name = "Ultimate Frisbee"
                        },
                        new
                        {
                            ExerciseId = 43,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "UprightRow.png",
                            Name = "Upright Row"
                        },
                        new
                        {
                            ExerciseId = 44,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Volleyball.png",
                            Name = "Volleyball"
                        },
                        new
                        {
                            ExerciseId = 45,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "WalkingWithStroller.png",
                            Name = "Walking with a Stroller"
                        },
                        new
                        {
                            ExerciseId = 46,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Yoga.png",
                            Name = "Yoga"
                        },
                        new
                        {
                            ExerciseId = 47,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "CalfStretch.png",
                            Name = "Calf Stretch"
                        },
                        new
                        {
                            ExerciseId = 48,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "HamstringStretch.png",
                            Name = "Hamstring Stretch"
                        },
                        new
                        {
                            ExerciseId = 49,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "QuadricepsStretch.png",
                            Name = "Quadriceps Stretch"
                        },
                        new
                        {
                            ExerciseId = 50,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "HipFlexorsStretch.png",
                            Name = "Hip Flexors Stretch"
                        },
                        new
                        {
                            ExerciseId = 51,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "KneeToChestStretch.png",
                            Name = "Knee-to-Chest Stretch"
                        },
                        new
                        {
                            ExerciseId = 52,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "ShoulderStretch.png",
                            Name = "Shoulder Stretch"
                        },
                        new
                        {
                            ExerciseId = 53,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "NeckStretch.png",
                            Name = "Neck Stretch"
                        },
                        new
                        {
                            ExerciseId = 54,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "TightropeWalk.png",
                            Name = "Tightrope Walk"
                        },
                        new
                        {
                            ExerciseId = 55,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "FlamingoStand.png",
                            Name = "Flamingo Stand"
                        },
                        new
                        {
                            ExerciseId = 56,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "HeelToToeWalk.png",
                            Name = "Heel-to-Toe Walk"
                        },
                        new
                        {
                            ExerciseId = 57,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "balance",
                            Image = "BandedTriplanarToeTaps.png",
                            Name = "Banded Triplanar Toe Taps"
                        },
                        new
                        {
                            ExerciseId = 58,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BenchPress.png",
                            Name = "Bench Press",
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 59,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "BicepCurl.png",
                            Name = "Bicep Curl",
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 60,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "strength_training",
                            Image = "ChestFly.png",
                            Name = "Chest Fly",
                            PlanId = 1
                        },
                        new
                        {
                            ExerciseId = 61,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Biking.png",
                            Name = "Biking",
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 62,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "Swimming.png",
                            Name = "Swimming",
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 63,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "aerobic",
                            Image = "JoggingOrRunning.png",
                            Name = "Jogging or Running",
                            PlanId = 2
                        },
                        new
                        {
                            ExerciseId = 64,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "HipFlexorsStretch.png",
                            Name = "Hip Flexors Stretch",
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 65,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "KneeToChestStretch.png",
                            Name = "Knee-to-Chest Stretch",
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 66,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "ShoulderStretch.png",
                            Name = "Shoulder Stretch",
                            PlanId = 3
                        },
                        new
                        {
                            ExerciseId = 67,
                            CreatedBy = "Better Built Systems",
                            ExerciseTypeID = "streching",
                            Image = "NeckStretch.png",
                            Name = "Neck Stretch",
                            PlanId = 3
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Property<string>("ExerciseTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseTypeID");

                    b.ToTable("ExerciseTypes");

                    b.HasData(
                        new
                        {
                            ExerciseTypeID = "aerobic",
                            Name = "Aerobic"
                        },
                        new
                        {
                            ExerciseTypeID = "strength_training",
                            Name = "Strength Training"
                        },
                        new
                        {
                            ExerciseTypeID = "streching",
                            Name = "Stretching"
                        },
                        new
                        {
                            ExerciseTypeID = "balance",
                            Name = "Balance"
                        },
                        new
                        {
                            ExerciseTypeID = "other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            CreatedBy = "Better Built Systems",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Example Plan 1",
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PlanId = 2,
                            CreatedBy = "Better Built Systems",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Example Plan 2",
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PlanId = 3,
                            CreatedBy = "Better Built Systems",
                            End = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Example Plan 3",
                            Start = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "6a299da0-8cce-487c-9340-acb0f9f5ae04",
                            ConcurrencyStamp = "6a299da0-8cce-487c-9340-acb0f9f5ae04",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "90a52f39-2660-4948-bcbc-77d12b727d3f",
                            ConcurrencyStamp = "90a52f39-2660-4948-bcbc-77d12b727d3f",
                            Name = "Suspended",
                            NormalizedName = "SUSPENDED"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "6de9e11d-f012-450a-8dc2-8ae58d510403",
                            RoleId = "6a299da0-8cce-487c-9340-acb0f9f5ae04"
                        },
                        new
                        {
                            UserId = "3e45d3e9-4d3c-4e20-9ace-e3d32a554134",
                            RoleId = "6a299da0-8cce-487c-9340-acb0f9f5ae04"
                        },
                        new
                        {
                            UserId = "f0f0ae27-d4f3-45ea-a383-e0a919a41462",
                            RoleId = "6a299da0-8cce-487c-9340-acb0f9f5ae04"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ExerciseType", "ExerciseType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("ExerciseType");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
