// <auto-generated />
using System;
using BetterBuiltWorkouts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BetterBuiltWorkouts.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220329201025_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "edeb89fe-2f9b-4b6d-b062-add2fd46e9a8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00855dab-cc68-47ed-a13b-9051812806d8",
                            Email = "drewxcom@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Drew",
                            LastName = "Crawford",
                            LockoutEnabled = false,
                            NormalizedEmail = "DREWXCOM@GMAIL.COM",
                            NormalizedUserName = "DREWXCOM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIbgd6gFSBAw777H27D2SoewT6Idv4bo+sEE6FZvPoSo86qnRT8UIFweskNSaW9gvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "28185a84-187f-464e-b06f-27f47c0f8f5b",
                            TwoFactorEnabled = false,
                            UserName = "drewxcom"
                        },
                        new
                        {
                            Id = "e32c76c4-526a-4756-9efe-7eb70b9c0a19",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3144e963-af3a-4677-89ee-fe0bc160af4a",
                            Email = "hale.l.c91@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Cody",
                            LastName = "Hale",
                            LockoutEnabled = false,
                            NormalizedEmail = "HALE.L.C91@GMAIL.COM",
                            NormalizedUserName = "CHALE",
                            PasswordHash = "AQAAAAEAACcQAAAAEMdg7M0QR6TegNqd+0hMzEO46ETtDjdGc3Y+park+kh7w61xTZZTzIfTkydz+mUVZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82adc4ab-4680-4773-88a8-8dcd050a08ab",
                            TwoFactorEnabled = false,
                            UserName = "chale"
                        },
                        new
                        {
                            Id = "15943deb-c8cb-4249-a7dc-a11f4f7b5c9f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87c8a391-9234-4fb2-b35a-e39240b2fbf1",
                            Email = "Karamuja.sabina@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sabina",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "KARAMUJA.SABINA@GMAIL.COM",
                            NormalizedUserName = "SKARAMUJA",
                            PasswordHash = "AQAAAAEAACcQAAAAEMTff0PqxIAcJpkdZhGzUT5Jigy12azAvPwja+k8vSzwdzcQnPT+yDiYKkcYPf1laA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae94b9ec-42cd-453f-9259-3b00472e5dd4",
                            TwoFactorEnabled = false,
                            UserName = "skaramuja"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("ExerciseTypeID");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            ExerciseTypeID = "strength_training",
                            Image = "BackExtension.png",
                            IsPublic = true,
                            Name = "Back Extension"
                        },
                        new
                        {
                            ExerciseId = 2,
                            ExerciseTypeID = "aerobic",
                            Image = "Basketball.png",
                            IsPublic = true,
                            Name = "Basketball"
                        },
                        new
                        {
                            ExerciseId = 3,
                            ExerciseTypeID = "strength_training",
                            Image = "BenchPress.png",
                            IsPublic = true,
                            Name = "Bench Press"
                        },
                        new
                        {
                            ExerciseId = 4,
                            ExerciseTypeID = "strength_training",
                            Image = "BicepCurl.png",
                            IsPublic = true,
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            ExerciseId = 5,
                            ExerciseTypeID = "aerobic",
                            Image = "Biking.png",
                            IsPublic = true,
                            Name = "Biking"
                        },
                        new
                        {
                            ExerciseId = 6,
                            ExerciseTypeID = "aerobic",
                            Image = "BriskWalking.png",
                            IsPublic = true,
                            Name = "Brisk Walking"
                        },
                        new
                        {
                            ExerciseId = 7,
                            ExerciseTypeID = "aerobic",
                            Image = "CardioClass.png",
                            IsPublic = true,
                            Name = "Cardio Class"
                        },
                        new
                        {
                            ExerciseId = 8,
                            ExerciseTypeID = "aerobic",
                            Image = "CardioMachine.png",
                            IsPublic = true,
                            Name = "Cardio Machine"
                        },
                        new
                        {
                            ExerciseId = 9,
                            ExerciseTypeID = "strength_training",
                            Image = "ChestFly.png",
                            IsPublic = true,
                            Name = "Chest Fly"
                        },
                        new
                        {
                            ExerciseId = 10,
                            ExerciseTypeID = "strength_training",
                            Image = "Crunches.png",
                            IsPublic = true,
                            Name = "Crunches"
                        },
                        new
                        {
                            ExerciseId = 11,
                            ExerciseTypeID = "aerobic",
                            Image = "Dancing.png",
                            IsPublic = true,
                            Name = "Dancing"
                        },
                        new
                        {
                            ExerciseId = 12,
                            ExerciseTypeID = "strength_training",
                            Image = "Deadlift.png",
                            IsPublic = true,
                            Name = "Deadlift"
                        },
                        new
                        {
                            ExerciseId = 13,
                            ExerciseTypeID = "aerobic",
                            Image = "GardeningAndWeeding.png",
                            IsPublic = true,
                            Name = "Gardening and Weeding"
                        },
                        new
                        {
                            ExerciseId = 14,
                            ExerciseTypeID = "aerobic",
                            Image = "Golf.png",
                            IsPublic = true,
                            Name = "Golf"
                        },
                        new
                        {
                            ExerciseId = 15,
                            ExerciseTypeID = "aerobic",
                            Image = "HighIntensityIntervalTraining.png",
                            IsPublic = true,
                            Name = "High-Intensity Interval Training"
                        },
                        new
                        {
                            ExerciseId = 16,
                            ExerciseTypeID = "aerobic",
                            Image = "Hiking.png",
                            IsPublic = true,
                            Name = "Hiking"
                        },
                        new
                        {
                            ExerciseId = 17,
                            ExerciseTypeID = "aerobic",
                            Image = "JoggingOrRunning.png",
                            IsPublic = true,
                            Name = "Jogging or Running"
                        },
                        new
                        {
                            ExerciseId = 18,
                            ExerciseTypeID = "strength_training",
                            Image = "LateralRaise.png",
                            IsPublic = true,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            ExerciseId = 19,
                            ExerciseTypeID = "strength_training",
                            Image = "LegCurl.png",
                            IsPublic = true,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            ExerciseId = 20,
                            ExerciseTypeID = "strength_training",
                            Image = "LegExtension.png",
                            IsPublic = true,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            ExerciseId = 21,
                            ExerciseTypeID = "strength_training",
                            Image = "LegPress.png",
                            IsPublic = true,
                            Name = "Leg Press"
                        },
                        new
                        {
                            ExerciseId = 22,
                            ExerciseTypeID = "strength_training",
                            Image = "Lunge.png",
                            IsPublic = true,
                            Name = "Lunge"
                        },
                        new
                        {
                            ExerciseId = 23,
                            ExerciseTypeID = "aerobic",
                            Image = "LiftingWeights.png",
                            IsPublic = true,
                            Name = "Lifting Weights"
                        },
                        new
                        {
                            ExerciseId = 24,
                            ExerciseTypeID = "balance",
                            Image = "Pilates.png",
                            IsPublic = true,
                            Name = "Pilates"
                        },
                        new
                        {
                            ExerciseId = 25,
                            ExerciseTypeID = "strength_training",
                            Image = "PullDown.png",
                            IsPublic = true,
                            Name = "Pull-down"
                        },
                        new
                        {
                            ExerciseId = 26,
                            ExerciseTypeID = "strength_training",
                            Image = "PullUp.png",
                            IsPublic = true,
                            Name = "Pull-up"
                        },
                        new
                        {
                            ExerciseId = 27,
                            ExerciseTypeID = "strength_training",
                            Image = "PushUps.png",
                            IsPublic = true,
                            Name = "Push-ups"
                        },
                        new
                        {
                            ExerciseId = 28,
                            ExerciseTypeID = "aerobic",
                            Image = "ResistanceExercise.png",
                            IsPublic = true,
                            Name = "Resistance Exercise with Elastic Bands or Tubes"
                        },
                        new
                        {
                            ExerciseId = 29,
                            ExerciseTypeID = "aerobic",
                            Image = "Rowing.png",
                            IsPublic = true,
                            Name = "Rowing"
                        },
                        new
                        {
                            ExerciseId = 30,
                            ExerciseTypeID = "strength_training",
                            Image = "SeatedCalfRaise.png",
                            IsPublic = true,
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 31,
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderPress.png",
                            IsPublic = true,
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            ExerciseId = 32,
                            ExerciseTypeID = "strength_training",
                            Image = "ShoulderShrug.png",
                            IsPublic = true,
                            Name = "Shoulder Shrug"
                        },
                        new
                        {
                            ExerciseId = 33,
                            ExerciseTypeID = "aerobic",
                            Image = "Soccer.png",
                            IsPublic = true,
                            Name = "Soccer"
                        },
                        new
                        {
                            ExerciseId = 34,
                            ExerciseTypeID = "strength_training",
                            Image = "Squat.png",
                            IsPublic = true,
                            Name = "Squat"
                        },
                        new
                        {
                            ExerciseId = 35,
                            ExerciseTypeID = "aerobic",
                            Image = "Stairs.png",
                            IsPublic = true,
                            Name = "Stairs"
                        },
                        new
                        {
                            ExerciseId = 36,
                            ExerciseTypeID = "strength_training",
                            Image = "StandingCalfRaise.png",
                            IsPublic = true,
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            ExerciseId = 37,
                            ExerciseTypeID = "aerobic",
                            Image = "StrengthClass.png",
                            IsPublic = true,
                            Name = "Strength Class"
                        },
                        new
                        {
                            ExerciseId = 38,
                            ExerciseTypeID = "aerobic",
                            Image = "Swimming.png",
                            IsPublic = true,
                            Name = "Swimming"
                        },
                        new
                        {
                            ExerciseId = 39,
                            ExerciseTypeID = "balance",
                            Image = "TaiChi.png",
                            IsPublic = true,
                            Name = "Tai Chi"
                        },
                        new
                        {
                            ExerciseId = 40,
                            ExerciseTypeID = "aerobic",
                            Image = "Tennis.png",
                            IsPublic = true,
                            Name = "Tennis"
                        },
                        new
                        {
                            ExerciseId = 41,
                            ExerciseTypeID = "strength_training",
                            Image = "TricepExtension.png",
                            IsPublic = true,
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            ExerciseId = 42,
                            ExerciseTypeID = "aerobic",
                            Image = "UltimateFrisbee.png",
                            IsPublic = true,
                            Name = "Ultimate Frisbee"
                        },
                        new
                        {
                            ExerciseId = 43,
                            ExerciseTypeID = "strength_training",
                            Image = "UprightRow.png",
                            IsPublic = true,
                            Name = "Upright Row"
                        },
                        new
                        {
                            ExerciseId = 44,
                            ExerciseTypeID = "aerobic",
                            Image = "Volleyball.png",
                            IsPublic = true,
                            Name = "Volleyball"
                        },
                        new
                        {
                            ExerciseId = 45,
                            ExerciseTypeID = "aerobic",
                            Image = "WalkingWithStroller.png",
                            IsPublic = true,
                            Name = "Walking with a Stroller"
                        },
                        new
                        {
                            ExerciseId = 46,
                            ExerciseTypeID = "aerobic",
                            Image = "Yoga.png",
                            IsPublic = true,
                            Name = "Yoga"
                        },
                        new
                        {
                            ExerciseId = 47,
                            ExerciseTypeID = "streching",
                            Image = "CalfStretch.png",
                            IsPublic = true,
                            Name = "Calf Stretch"
                        },
                        new
                        {
                            ExerciseId = 48,
                            ExerciseTypeID = "streching",
                            Image = "HamstringStretch.png",
                            IsPublic = true,
                            Name = "Hamstring Stretch"
                        },
                        new
                        {
                            ExerciseId = 49,
                            ExerciseTypeID = "streching",
                            Image = "QuadricepsStretch.png",
                            IsPublic = true,
                            Name = "Quadriceps Stretch"
                        },
                        new
                        {
                            ExerciseId = 50,
                            ExerciseTypeID = "streching",
                            Image = "HipFlexorsStretch.png",
                            IsPublic = true,
                            Name = "Hip Flexors Stretch"
                        },
                        new
                        {
                            ExerciseId = 51,
                            ExerciseTypeID = "streching",
                            Image = "KneeToChestStretch.png",
                            IsPublic = true,
                            Name = "Knee-to-Chest Stretch"
                        },
                        new
                        {
                            ExerciseId = 52,
                            ExerciseTypeID = "streching",
                            Image = "ShoulderStretch.png",
                            IsPublic = true,
                            Name = "Shoulder Stretch"
                        },
                        new
                        {
                            ExerciseId = 53,
                            ExerciseTypeID = "streching",
                            Image = "NeckStretch.png",
                            IsPublic = true,
                            Name = "Neck Stretch"
                        },
                        new
                        {
                            ExerciseId = 54,
                            ExerciseTypeID = "balance",
                            Image = "TightropeWalk.png",
                            IsPublic = true,
                            Name = "Tightrope Walk"
                        },
                        new
                        {
                            ExerciseId = 55,
                            ExerciseTypeID = "balance",
                            Image = "FlamingoStand.png",
                            IsPublic = true,
                            Name = "Flamingo Stand"
                        },
                        new
                        {
                            ExerciseId = 56,
                            ExerciseTypeID = "balance",
                            Image = "HeelToToeWalk.png",
                            IsPublic = true,
                            Name = "Heel-to-Toe Walk"
                        },
                        new
                        {
                            ExerciseId = 57,
                            ExerciseTypeID = "balance",
                            Image = "BandedTriplanarToeTaps.png",
                            IsPublic = true,
                            Name = "Banded Triplanar Toe Taps"
                        });
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.ExerciseType", b =>
                {
                    b.Property<string>("ExerciseTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseTypeID");

                    b.ToTable("ExerciseTypes");

                    b.HasData(
                        new
                        {
                            ExerciseTypeID = "aerobic",
                            Name = "Aerobic"
                        },
                        new
                        {
                            ExerciseTypeID = "strength_training",
                            Name = "Strength Training"
                        },
                        new
                        {
                            ExerciseTypeID = "streching",
                            Name = "Stretching"
                        },
                        new
                        {
                            ExerciseTypeID = "balance",
                            Name = "Balance"
                        },
                        new
                        {
                            ExerciseTypeID = "other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "d8304918-f365-4d4c-b53d-1d76d7452041",
                            ConcurrencyStamp = "d8304918-f365-4d4c-b53d-1d76d7452041",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a16e8a3d-e5c6-454e-9c93-f9181ee981db",
                            ConcurrencyStamp = "a16e8a3d-e5c6-454e-9c93-f9181ee981db",
                            Name = "Suspended",
                            NormalizedName = "SUSPENDED"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "edeb89fe-2f9b-4b6d-b062-add2fd46e9a8",
                            RoleId = "d8304918-f365-4d4c-b53d-1d76d7452041"
                        },
                        new
                        {
                            UserId = "e32c76c4-526a-4756-9efe-7eb70b9c0a19",
                            RoleId = "d8304918-f365-4d4c-b53d-1d76d7452041"
                        },
                        new
                        {
                            UserId = "15943deb-c8cb-4249-a7dc-a11f4f7b5c9f",
                            RoleId = "d8304918-f365-4d4c-b53d-1d76d7452041"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BetterBuiltWorkouts.Models.Exercise", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeID");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BetterBuiltWorkouts.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
